version: '2'

services:
    jenkins:
        build: .
        user: jenkins
        volumes:
            - ~/opt/jenkins:/var/jenkins_home
        ports:
            - "8080:8080"
            - "50000:50000"
